apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260622-200216-rlhth1vc67wj-service
spec:
  selector:
    app: enterprise-system-20260622-200216-rlhth1vc67wj
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
